name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'ivy-dev-sample-shop'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          region: eu
          stack: heroku-22
          buildpack: heroku/nodejs
